#include "config_loader.h"
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <map>
#include <sstream>
#include <stdexcept>
namespace { struct J{enum T{N,Num,B,Str,Obj,Arr}t=N;double n=0;bool b=false;std::string s;std::map<std::string,J>o;std::vector<J>a;const J&at(const std::string&k)const{auto i=o.find(k);if(i==o.end())throw std::runtime_error("missing JSON key: "+k);return i->second;}};
class P{const std::string&x;size_t i=0;void ws(){while(i<x.size()&&std::isspace((unsigned char)x[i]))++i;}J val(){ws();if(i>=x.size())throw std::runtime_error("unexpected JSON end");if(x[i]=='{')return obj();if(x[i]=='[')return arr();if(x[i]=='\"')return str();if(x.compare(i,4,"true")==0){i+=4;J z;z.t=J::B;z.b=true;return z;}if(x.compare(i,5,"false")==0){i+=5;J z;z.t=J::B;return z;}if(x.compare(i,4,"null")==0){i+=4;return{};}char*e=nullptr;double n=std::strtod(x.c_str()+i,&e);if(e==x.c_str()+i)throw std::runtime_error("invalid JSON value");i=(size_t)(e-x.c_str());J z;z.t=J::Num;z.n=n;return z;}J str(){J z;z.t=J::Str;++i;while(i<x.size()&&x[i]!='\"'){if(x[i]=='\\'&&i+1<x.size())++i;z.s+=x[i++];}if(i==x.size())throw std::runtime_error("unterminated JSON string");++i;return z;}J arr(){J z;z.t=J::Arr;++i;ws();if(i<x.size()&&x[i]==']'){++i;return z;}for(;;){z.a.push_back(val());ws();if(i<x.size()&&x[i]==']'){++i;return z;}if(i>=x.size()||x[i++]!=',')throw std::runtime_error("expected JSON comma");}}J obj(){J z;z.t=J::Obj;++i;ws();if(i<x.size()&&x[i]=='}'){++i;return z;}for(;;){ws();J k=str();ws();if(i>=x.size()||x[i++]!=':')throw std::runtime_error("expected JSON colon");z.o[k.s]=val();ws();if(i<x.size()&&x[i]=='}'){++i;return z;}if(i>=x.size()||x[i++]!=',')throw std::runtime_error("expected JSON comma");}}public:explicit P(const std::string&s):x(s){}J parse(){return val();}};
float f(const J&j){return(float)j.n;}std::array<float,4> color(const J&j){std::array<float,4>c{0,0,0,1};for(size_t i=0;i<j.a.size()&&i<4;++i)c[i]=f(j.a[i]);return c;}}
OverlayConfig loadOverlayConfig(const std::string&path){std::ifstream in(path);if(!in)throw std::runtime_error("cannot open overlay config: "+path);std::stringstream ss;ss<<in.rdbuf();std::string raw=ss.str();J r=P(raw).parse();OverlayConfig c;const J&t=r.at("table");c.tableWidth=f(t.at("width"));c.tableHeight=f(t.at("height"));c.ballRadius=f(t.at("ballRadius"));c.pocketRadius=f(t.at("pocketRadius"));for(const J&p:t.at("pockets").a)c.pockets.push_back({p.at("x").n,p.at("y").n});const J&w=r.at("window");c.windowWidth=(int)w.at("width").n;c.windowHeight=(int)w.at("height").n;c.windowX=(int)w.at("x").n;c.windowY=(int)w.at("y").n;c.opacity=f(w.at("opacity"));c.clickThrough=w.at("clickThrough").b;const J&co=r.at("colors");c.table=color(co.at("table"));c.rail=color(co.at("rail"));c.pocket=color(co.at("pocket"));c.trajectory=color(co.at("trajectory"));c.ball=color(co.at("ball"));c.cue=color(co.at("cue"));c.statusOn=color(co.at("statusOn"));c.statusOff=color(co.at("statusOff"));return c;}
